//
//  TrackListMetadata.h
//
//  Generated by JSON Model Generator v0.0.2 on Sun Dec 28 07:17:20 MST 2014.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

#import "TrackListMetadataTracks.h"
@interface TrackListMetadata : NSObject

//
// Properties
//

@property (nonatomic) NSInteger tCalories;
@property (nonatomic) double tDescDist;
@property (nonatomic) double tDist;
@property (nonatomic) double tMaxSpeed;
@property (nonatomic) double tVert;
@property (nonatomic, strong) NSMutableArray *tracks;


/**
 * Converts this TrackListMetadata to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this TrackListMetadata to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this TrackListMetadata to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a TrackListMetadata.
 */
+(TrackListMetadata *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a TrackListMetadata.
 */
+(TrackListMetadata *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of TrackListMetadata.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of TrackListMetadata to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

