//
//  Track.h
//
//  Generated by JSON Model Generator v0.0.2 on Sun Dec 28 07:17:18 MST 2014.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

#import "TrackKeyPoints.h"
#import "TrackPoints.h"
@interface Track : NSObject

//
// Properties
//

@property (nonatomic) double asc;
@property (nonatomic) double desc;
@property (nonatomic) BOOL dirty;
@property (nonatomic) double dist;
@property (nonatomic) NSInteger dur;
@property (nonatomic, strong) NSString *filename;
@property (nonatomic, strong) NSMutableArray *keyPoints;
@property (nonatomic) double maxAlt;
@property (nonatomic) double maxSpeed;
@property (nonatomic) double minAlt;
@property (nonatomic, strong) NSString *name;
@property (nonatomic, strong) NSMutableArray *points;
@property (nonatomic) NSInteger runs;


/**
 * Converts this Track to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this Track to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this Track to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a Track.
 */
+(Track *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a Track.
 */
+(Track *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of Track.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of Track to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

