//
//  TrackLog.h
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

@interface TrackLog : NSObject

//
// Properties
//

@property (nonatomic) double time;
@property (nonatomic, strong) NSString *class;
@property (nonatomic, strong) NSString *method;
@property (nonatomic) NSInteger line;
@property (nonatomic, strong) NSString *level;
@property (nonatomic, strong) NSString *theDescription;


/**
 * Converts this TrackLog to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this TrackLog to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this TrackLog to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a TrackLog.
 */
+(TrackLog *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a TrackLog.
 */
+(TrackLog *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of TrackLog.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of TrackLog to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

