//
//  TrackMetadataListTracks.m
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:21 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import "TrackMetadataListTracks.h"
#import "Serializer.h"

#define SERIALIZE_CALORIES @"calories"
#define SERIALIZE_DATE @"date"
#define SERIALIZE_DIRTY @"dirty"
#define SERIALIZE_DISTANCE @"distance"
#define SERIALIZE_DURATION @"duration"
#define SERIALIZE_FILE @"file"
#define SERIALIZE_ID @"id"
#define SERIALIZE_MAX_ALT @"max_alt"
#define SERIALIZE_METADATA_ID @"metadataId"
#define SERIALIZE_MIN_ALT @"min_alt"
#define SERIALIZE_NAME @"name"
#define SERIALIZE_RUNS @"runs"
#define SERIALIZE_SPEED @"speed"
#define SERIALIZE_VERT_IN_METERS @"vertInMeters"
#define SERIALIZE_VERT_DISTANCE @"vert_distance"


@implementation TrackMetadataListTracks

#pragma mark Serialization Methods

-(NSDictionary *)toDictionary {
	NSMutableDictionary *dict = [[NSMutableDictionary alloc]init];

	[Serializer setDict:dict intValue:self.calories forKey:SERIALIZE_CALORIES];
	[Serializer setDict:dict object:self.date forKey:SERIALIZE_DATE];
	[Serializer setDict:dict boolValue:self.dirty forKey:SERIALIZE_DIRTY];
	[Serializer setDict:dict doubleValue:self.distance forKey:SERIALIZE_DISTANCE];
	[Serializer setDict:dict intValue:self.duration forKey:SERIALIZE_DURATION];
	[Serializer setDict:dict object:self.file forKey:SERIALIZE_FILE];
	[Serializer setDict:dict object:self.theId forKey:SERIALIZE_ID];
	[Serializer setDict:dict doubleValue:self.maxAlt forKey:SERIALIZE_MAX_ALT];
	[Serializer setDict:dict object:self.metadataId forKey:SERIALIZE_METADATA_ID];
	[Serializer setDict:dict doubleValue:self.minAlt forKey:SERIALIZE_MIN_ALT];
	[Serializer setDict:dict object:self.name forKey:SERIALIZE_NAME];
	[Serializer setDict:dict intValue:self.runs forKey:SERIALIZE_RUNS];
	[Serializer setDict:dict doubleValue:self.speed forKey:SERIALIZE_SPEED];
	[Serializer setDict:dict doubleValue:self.vertInMeters forKey:SERIALIZE_VERT_IN_METERS];
	[Serializer setDict:dict doubleValue:self.vertDistance forKey:SERIALIZE_VERT_DISTANCE];

	return dict;
}

-(NSString *)toJson {
	return [self toJson:NO];
}

-(NSString *)toJson:(BOOL)pretty {
	NSDictionary *dict = [self toDictionary];

	return [Serializer jsonStringFromDictionary:dict withPrettyPrint:pretty];

}

+ (TrackMetadataListTracks *)fromDictionary:(NSDictionary *)dict {
	TrackMetadataListTracks *object = [[TrackMetadataListTracks alloc]init];
	object.calories = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_CALORIES orDefaultTo:0];
	object.date = [Serializer safeGetDictString:dict withKey:SERIALIZE_DATE];
	object.dirty = [Serializer getBoolFromDict:dict forKey:SERIALIZE_DIRTY orDefaultTo:NO];
	object.distance = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_DISTANCE orDefaultTo:0.0];
	object.duration = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_DURATION orDefaultTo:0];
	object.file = [Serializer safeGetDictString:dict withKey:SERIALIZE_FILE];
	object.theId = [Serializer safeGetDictString:dict withKey:SERIALIZE_ID];
	object.maxAlt = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_MAX_ALT orDefaultTo:0.0];
	object.metadataId = [Serializer safeGetDictString:dict withKey:SERIALIZE_METADATA_ID];
	object.minAlt = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_MIN_ALT orDefaultTo:0.0];
	object.name = [Serializer safeGetDictString:dict withKey:SERIALIZE_NAME];
	object.runs = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_RUNS orDefaultTo:0];
	object.speed = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_SPEED orDefaultTo:0.0];
	object.vertInMeters = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_VERT_IN_METERS orDefaultTo:0.0];
	object.vertDistance = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_VERT_DISTANCE orDefaultTo:0.0];
	return object;
}

+(TrackMetadataListTracks *)fromJsonString:(NSString *)json {
	NSDictionary *dict = [Serializer fromJsonString:json];
	return [TrackMetadataListTracks fromDictionary:dict];
}

+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for (NSDictionary *dict in array) {
        [result addObject:[TrackMetadataListTracks fromDictionary:dict]];
    }
    
    return result;
}

+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for(TrackMetadataListTracks *object in array) {
        [result addObject:[object toDictionary]];
    }
    
    return result;
}

@end

