//
//  TrackKeyPoints.m
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import "TrackKeyPoints.h"
#import "Serializer.h"

#define SERIALIZE_DIR @"dir"
#define SERIALIZE_DIST @"dist"
#define SERIALIZE_DURATION @"duration"
#define SERIALIZE_IDX_END @"idx_end"
#define SERIALIZE_IDX_START @"idx_start"
#define SERIALIZE_MAX_ELEV @"max_elev"
#define SERIALIZE_MAX_SPEED @"max_speed"
#define SERIALIZE_MIN_ELEV @"min_elev"
#define SERIALIZE_V_DELTA @"v_delta"
#define SERIALIZE_DESCRIPTION @"description"
#define SERIALIZE_TYPE @"type"


@implementation TrackKeyPoints

#pragma mark Serialization Methods

-(NSDictionary *)toDictionary {
	NSMutableDictionary *dict = [[NSMutableDictionary alloc]init];

	[Serializer setDict:dict intValue:self.dir forKey:SERIALIZE_DIR];
	[Serializer setDict:dict doubleValue:self.dist forKey:SERIALIZE_DIST];
	[Serializer setDict:dict doubleValue:self.duration forKey:SERIALIZE_DURATION];
	[Serializer setDict:dict intValue:self.idxEnd forKey:SERIALIZE_IDX_END];
	[Serializer setDict:dict intValue:self.idxStart forKey:SERIALIZE_IDX_START];
	[Serializer setDict:dict doubleValue:self.maxElev forKey:SERIALIZE_MAX_ELEV];
	[Serializer setDict:dict doubleValue:self.maxSpeed forKey:SERIALIZE_MAX_SPEED];
	[Serializer setDict:dict doubleValue:self.minElev forKey:SERIALIZE_MIN_ELEV];
	[Serializer setDict:dict doubleValue:self.vDelta forKey:SERIALIZE_V_DELTA];
	[Serializer setDict:dict object:self.theDescription forKey:SERIALIZE_DESCRIPTION];
	[Serializer setDict:dict object:self.type forKey:SERIALIZE_TYPE];

	return dict;
}

-(NSString *)toJson {
	return [self toJson:NO];
}

-(NSString *)toJson:(BOOL)pretty {
	NSDictionary *dict = [self toDictionary];

	return [Serializer jsonStringFromDictionary:dict withPrettyPrint:pretty];

}

+ (TrackKeyPoints *)fromDictionary:(NSDictionary *)dict {
	TrackKeyPoints *object = [[TrackKeyPoints alloc]init];
	object.dir = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_DIR orDefaultTo:0];
	object.dist = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_DIST orDefaultTo:0.0];
	object.duration = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_DURATION orDefaultTo:0.0];
	object.idxEnd = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_IDX_END orDefaultTo:0];
	object.idxStart = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_IDX_START orDefaultTo:0];
	object.maxElev = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_MAX_ELEV orDefaultTo:0.0];
	object.maxSpeed = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_MAX_SPEED orDefaultTo:0.0];
	object.minElev = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_MIN_ELEV orDefaultTo:0.0];
	object.vDelta = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_V_DELTA orDefaultTo:0.0];
	object.theDescription = [Serializer safeGetDictString:dict withKey:SERIALIZE_DESCRIPTION];
	object.type = [Serializer safeGetDictString:dict withKey:SERIALIZE_TYPE];
	return object;
}

+(TrackKeyPoints *)fromJsonString:(NSString *)json {
	NSDictionary *dict = [Serializer fromJsonString:json];
	return [TrackKeyPoints fromDictionary:dict];
}

+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for (NSDictionary *dict in array) {
        [result addObject:[TrackKeyPoints fromDictionary:dict]];
    }
    
    return result;
}

+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for(TrackKeyPoints *object in array) {
        [result addObject:[object toDictionary]];
    }
    
    return result;
}

@end

