//
//  TrackListMetadata.m
//
//  Generated by JSON Model Generator v0.0.2 on Sun Dec 28 07:17:20 MST 2014.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import "TrackListMetadata.h"
#import "Serializer.h"

#define SERIALIZE_T_CALORIES @"t_calories"
#define SERIALIZE_T_DESC_DIST @"t_desc_dist"
#define SERIALIZE_T_DIST @"t_dist"
#define SERIALIZE_T_MAX_SPEED @"t_max_speed"
#define SERIALIZE_T_VERT @"t_vert"
#define SERIALIZE_TRACKS @"tracks"


@implementation TrackListMetadata

#pragma mark Serialization Methods

-(NSDictionary *)toDictionary {
	NSMutableDictionary *dict = [[NSMutableDictionary alloc]init];

	[Serializer setDict:dict intValue:self.tCalories forKey:SERIALIZE_T_CALORIES];
	[Serializer setDict:dict doubleValue:self.tDescDist forKey:SERIALIZE_T_DESC_DIST];
	[Serializer setDict:dict doubleValue:self.tDist forKey:SERIALIZE_T_DIST];
	[Serializer setDict:dict doubleValue:self.tMaxSpeed forKey:SERIALIZE_T_MAX_SPEED];
	[Serializer setDict:dict doubleValue:self.tVert forKey:SERIALIZE_T_VERT];
	[Serializer setDict:dict object:[TrackListMetadataTracks toArrayOfDictionaries:self.tracks] forKey:SERIALIZE_TRACKS];

	return dict;
}

-(NSString *)toJson {
	return [self toJson:NO];
}

-(NSString *)toJson:(BOOL)pretty {
	NSDictionary *dict = [self toDictionary];

	return [Serializer jsonStringFromDictionary:dict withPrettyPrint:pretty];

}

+ (TrackListMetadata *)fromDictionary:(NSDictionary *)dict {
	TrackListMetadata *object = [[TrackListMetadata alloc]init];
	object.tCalories = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_T_CALORIES orDefaultTo:0];
	object.tDescDist = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_T_DESC_DIST orDefaultTo:0.0];
	object.tDist = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_T_DIST orDefaultTo:0.0];
	object.tMaxSpeed = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_T_MAX_SPEED orDefaultTo:0.0];
	object.tVert = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_T_VERT orDefaultTo:0.0];
	object.tracks = [TrackListMetadataTracks fromArrayOfDictionaries:[Serializer getArrayFromDict:dict forKey:SERIALIZE_TRACKS]];
	return object;
}

+(TrackListMetadata *)fromJsonString:(NSString *)json {
	NSDictionary *dict = [Serializer fromJsonString:json];
	return [TrackListMetadata fromDictionary:dict];
}

+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for (NSDictionary *dict in array) {
        [result addObject:[TrackListMetadata fromDictionary:dict]];
    }
    
    return result;
}

+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for(TrackListMetadata *object in array) {
        [result addObject:[object toDictionary]];
    }
    
    return result;
}

@end

