//
//  TrackMetadataListTracks.h
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:21 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

@interface TrackMetadataListTracks : NSObject

//
// Properties
//

@property (nonatomic) NSInteger calories;
@property (nonatomic, strong) NSString *date;
@property (nonatomic) BOOL dirty;
@property (nonatomic) double distance;
@property (nonatomic) NSInteger duration;
@property (nonatomic, strong) NSString *file;
@property (nonatomic, strong) NSString *theId;
@property (nonatomic) double maxAlt;
@property (nonatomic, strong) NSString *metadataId;
@property (nonatomic) double minAlt;
@property (nonatomic, strong) NSString *name;
@property (nonatomic) NSInteger runs;
@property (nonatomic) double speed;
@property (nonatomic) double vertInMeters;
@property (nonatomic) double vertDistance;


/**
 * Converts this TrackMetadataListTracks to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this TrackMetadataListTracks to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this TrackMetadataListTracks to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a TrackMetadataListTracks.
 */
+(TrackMetadataListTracks *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a TrackMetadataListTracks.
 */
+(TrackMetadataListTracks *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of TrackMetadataListTracks.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of TrackMetadataListTracks to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

