//
//  Track.h
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

#import "TrackKeyPoints.h"
#import "TrackPoints.h"
#import "TrackLog.h"
@interface Track : NSObject

//
// Properties
//

@property (nonatomic) double asc;
@property (nonatomic) double desc;
@property (nonatomic) BOOL dirty;
@property (nonatomic) double dist;
@property (nonatomic) NSInteger dur;
@property (nonatomic, strong) NSString *filename;
@property (nonatomic, strong) NSString *theId;
@property (nonatomic, strong) NSMutableArray *keyPoints;		// Array of TrackKeyPoints Objects
@property (nonatomic) double maxAlt;
@property (nonatomic) double maxSpeed;
@property (nonatomic, strong) NSString *metadataId;
@property (nonatomic) double minAlt;
@property (nonatomic, strong) NSString *name;
@property (nonatomic, strong) NSMutableArray *points;		// Array of TrackPoints Objects
@property (nonatomic) NSInteger runs;
@property (nonatomic, strong) NSString *appVersion;
@property (nonatomic, strong) NSMutableArray *log;		// Array of TrackLog Objects


/**
 * Converts this Track to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this Track to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this Track to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a Track.
 */
+(Track *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a Track.
 */
+(Track *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of Track.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of Track to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

