//
//  TrackPoints.m
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import "TrackPoints.h"
#import "Serializer.h"

#define SERIALIZE_ALT @"alt"
#define SERIALIZE_DIST @"dist"
#define SERIALIZE_H_ACC @"h_acc"
#define SERIALIZE_LAT @"lat"
#define SERIALIZE_LON @"lon"
#define SERIALIZE_SPEED @"speed"
#define SERIALIZE_TIME @"time"
#define SERIALIZE_V_ACC @"v_acc"


@implementation TrackPoints

#pragma mark Serialization Methods

-(NSDictionary *)toDictionary {
	NSMutableDictionary *dict = [[NSMutableDictionary alloc]init];

	[Serializer setDict:dict doubleValue:self.alt forKey:SERIALIZE_ALT];
	[Serializer setDict:dict intValue:self.dist forKey:SERIALIZE_DIST];
	[Serializer setDict:dict intValue:self.hAcc forKey:SERIALIZE_H_ACC];
	[Serializer setDict:dict doubleValue:self.lat forKey:SERIALIZE_LAT];
	[Serializer setDict:dict doubleValue:self.lon forKey:SERIALIZE_LON];
	[Serializer setDict:dict doubleValue:self.speed forKey:SERIALIZE_SPEED];
	[Serializer setDict:dict doubleValue:self.time forKey:SERIALIZE_TIME];
	[Serializer setDict:dict intValue:self.vAcc forKey:SERIALIZE_V_ACC];

	return dict;
}

-(NSString *)toJson {
	return [self toJson:NO];
}

-(NSString *)toJson:(BOOL)pretty {
	NSDictionary *dict = [self toDictionary];

	return [Serializer jsonStringFromDictionary:dict withPrettyPrint:pretty];

}

+ (TrackPoints *)fromDictionary:(NSDictionary *)dict {
	TrackPoints *object = [[TrackPoints alloc]init];
	object.alt = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_ALT orDefaultTo:0.0];
	object.dist = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_DIST orDefaultTo:0];
	object.hAcc = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_H_ACC orDefaultTo:0];
	object.lat = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_LAT orDefaultTo:0.0];
	object.lon = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_LON orDefaultTo:0.0];
	object.speed = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_SPEED orDefaultTo:0.0];
	object.time = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_TIME orDefaultTo:0.0];
	object.vAcc = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_V_ACC orDefaultTo:0];
	return object;
}

+(TrackPoints *)fromJsonString:(NSString *)json {
	NSDictionary *dict = [Serializer fromJsonString:json];
	return [TrackPoints fromDictionary:dict];
}

+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for (NSDictionary *dict in array) {
        [result addObject:[TrackPoints fromDictionary:dict]];
    }
    
    return result;
}

+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for(TrackPoints *object in array) {
        [result addObject:[object toDictionary]];
    }
    
    return result;
}

@end

