//
//  TrackMetadataList.h
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:21 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

#import "TrackMetadataListTracks.h"
@interface TrackMetadataList : NSObject

//
// Properties
//

@property (nonatomic) NSInteger tCalories;
@property (nonatomic) double tDescDist;
@property (nonatomic) double tDist;
@property (nonatomic) double tMaxSpeed;
@property (nonatomic) double tVert;
@property (nonatomic, strong) NSMutableArray *tracks;		// Array of TrackMetadataListTracks Objects


/**
 * Converts this TrackMetadataList to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this TrackMetadataList to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this TrackMetadataList to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a TrackMetadataList.
 */
+(TrackMetadataList *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a TrackMetadataList.
 */
+(TrackMetadataList *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of TrackMetadataList.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of TrackMetadataList to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

