//
//  TrackLog.m
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import "TrackLog.h"
#import "Serializer.h"

#define SERIALIZE_TIME @"time"
#define SERIALIZE_CLASS @"class"
#define SERIALIZE_METHOD @"method"
#define SERIALIZE_LINE @"line"
#define SERIALIZE_LEVEL @"level"
#define SERIALIZE_DESCRIPTION @"description"


@implementation TrackLog

#pragma mark Serialization Methods

-(NSDictionary *)toDictionary {
	NSMutableDictionary *dict = [[NSMutableDictionary alloc]init];

	[Serializer setDict:dict doubleValue:self.time forKey:SERIALIZE_TIME];
	[Serializer setDict:dict object:self.class forKey:SERIALIZE_CLASS];
	[Serializer setDict:dict object:self.method forKey:SERIALIZE_METHOD];
	[Serializer setDict:dict intValue:self.line forKey:SERIALIZE_LINE];
	[Serializer setDict:dict object:self.level forKey:SERIALIZE_LEVEL];
	[Serializer setDict:dict object:self.theDescription forKey:SERIALIZE_DESCRIPTION];

	return dict;
}

-(NSString *)toJson {
	return [self toJson:NO];
}

-(NSString *)toJson:(BOOL)pretty {
	NSDictionary *dict = [self toDictionary];

	return [Serializer jsonStringFromDictionary:dict withPrettyPrint:pretty];

}

+ (TrackLog *)fromDictionary:(NSDictionary *)dict {
	TrackLog *object = [[TrackLog alloc]init];
	object.time = [Serializer getDoubleFromDict:dict forKey:SERIALIZE_TIME orDefaultTo:0.0];
	object.class = [Serializer safeGetDictString:dict withKey:SERIALIZE_CLASS];
	object.method = [Serializer safeGetDictString:dict withKey:SERIALIZE_METHOD];
	object.line = [Serializer getIntegerFromDict:dict forKey:SERIALIZE_LINE orDefaultTo:0];
	object.level = [Serializer safeGetDictString:dict withKey:SERIALIZE_LEVEL];
	object.theDescription = [Serializer safeGetDictString:dict withKey:SERIALIZE_DESCRIPTION];
	return object;
}

+(TrackLog *)fromJsonString:(NSString *)json {
	NSDictionary *dict = [Serializer fromJsonString:json];
	return [TrackLog fromDictionary:dict];
}

+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for (NSDictionary *dict in array) {
        [result addObject:[TrackLog fromDictionary:dict]];
    }
    
    return result;
}

+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array {
    NSMutableArray *result = [[NSMutableArray alloc]init];
    
    for(TrackLog *object in array) {
        [result addObject:[object toDictionary]];
    }
    
    return result;
}

@end

