//
//  TrackKeyPoints.h
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

@interface TrackKeyPoints : NSObject

//
// Properties
//

@property (nonatomic) NSInteger dir;
@property (nonatomic) double dist;
@property (nonatomic) double duration;
@property (nonatomic) NSInteger idxEnd;
@property (nonatomic) NSInteger idxStart;
@property (nonatomic) double maxElev;
@property (nonatomic) double maxSpeed;
@property (nonatomic) double minElev;
@property (nonatomic) double vDelta;
@property (nonatomic, strong) NSString *theDescription;
@property (nonatomic, strong) NSString *type;


/**
 * Converts this TrackKeyPoints to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this TrackKeyPoints to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this TrackKeyPoints to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a TrackKeyPoints.
 */
+(TrackKeyPoints *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a TrackKeyPoints.
 */
+(TrackKeyPoints *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of TrackKeyPoints.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of TrackKeyPoints to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

