//
//  TrackListMetadataTracks.h
//
//  Generated by JSON Model Generator v0.0.2 on Sun Dec 28 07:17:20 MST 2014.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <Foundation/Foundation.h>

@interface TrackListMetadataTracks : NSObject

//
// Properties
//

@property (nonatomic) NSInteger calories;
@property (nonatomic, strong) NSString *date;
@property (nonatomic) BOOL dirty;
@property (nonatomic) double distance;
@property (nonatomic) NSInteger duration;
@property (nonatomic, strong) NSString *file;
@property (nonatomic, strong) NSString *theId;
@property (nonatomic) double maxAlt;
@property (nonatomic) double minAlt;
@property (nonatomic, strong) NSString *name;
@property (nonatomic) NSInteger runs;
@property (nonatomic) double speed;
@property (nonatomic) double vert;
@property (nonatomic) double vertDistance;


/**
 * Converts this TrackListMetadataTracks to a NSDictionary object (as a serialization mechanism).
 */
-(NSDictionary *)toDictionary;

/**
 * Converts this TrackListMetadataTracks to a JSON String (as a serializaton mechanism).
 */
-(NSString *)toJson;
/**
 * Converts this TrackListMetadataTracks to a JSON String (as a serialization mechanism) with optional pretty print.
 */
-(NSString *)toJson:(BOOL)pretty;

/**
 * "Deserializes" the provided dictionary into a TrackListMetadataTracks.
 */
+(TrackListMetadataTracks *)fromDictionary:(NSDictionary *)dict;

/**
 * Deserializes the provided JSON String into a TrackListMetadataTracks.
 */
+(TrackListMetadataTracks *)fromJsonString:(NSString *)json;
/**
 * "Deserializes" the provided array of dictionaries into an array of TrackListMetadataTracks.
 */
+(NSMutableArray *)fromArrayOfDictionaries:(NSArray *)array;

/**
 * "Serializes" the provided Array of TrackListMetadataTracks to an Array of Dictionaries.
 */
+(NSMutableArray *)toArrayOfDictionaries:(NSArray *)array;

@end

