//
//  TrackMetadataListTest.m
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:21 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <XCTest/XCTest.h>
#import "TrackMetadataList.h"
#import "Serializer.h"

@interface TrackMetadataListTest : XCTestCase{
	NSString *sampleJson;
	TrackMetadataList *deserialized;
}
@end

#define DATE_LONG 1411065116782
#define DATE_ISO @"2014-09-18T11:31:56.782-07:00"
#define DATE_ZULU @"2014-09-18T11:31:56.782Z"
#define TEST_KEY @"date"

@implementation TrackMetadataListTest

- (void)setUp
{
	[super setUp];
	NSString *pathToResource = [[NSBundle bundleForClass:self.class] pathForResource:@"track_metadata_list" ofType:@"json"];
	NSError *error = nil;
	sampleJson = [NSString stringWithContentsOfFile:pathToResource encoding:NSUTF8StringEncoding error:&error];
	if(error) {
		XCTFail(@"Failed to load file: contests.json: %@", error.localizedDescription);
	}
	NSDictionary *dict = [Serializer fromJsonString:sampleJson];
	deserialized = [TrackMetadataList fromDictionary:dict];
	XCTAssertNotNil(deserialized, @"The TrackMetadataList failed to deserialize properly");
}

- (void)tearDown
{
    // Put teardown code here; it will be run once, after the last test case.
    [super tearDown];
}

-(void)testTCalories {
	XCTAssertEqual((NSInteger)0, deserialized.tCalories, @"Failed to properly deserialize the tCalories");
}

-(void)testTDescDist {
	XCTAssertEqualWithAccuracy(530750.0762603137, deserialized.tDescDist, 0.01, @"Failed to properly deserialize the tDescDist");
}

-(void)testTDist {
	XCTAssertEqualWithAccuracy(1013094.065601146, deserialized.tDist, 0.01, @"Failed to properly deserialize the tDist");
}

-(void)testTMaxSpeed {
	XCTAssertEqualWithAccuracy(8970.610839622299, deserialized.tMaxSpeed, 0.01, @"Failed to properly deserialize the tMaxSpeed");
}

-(void)testTVert {
	XCTAssertEqualWithAccuracy(61429.19433979907, deserialized.tVert, 0.01, @"Failed to properly deserialize the tVert");
}

@end
