//
//  TrackLogTest.m
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <XCTest/XCTest.h>
#import "TrackLog.h"
#import "Serializer.h"

@interface TrackLogTest : XCTestCase{
	NSString *sampleJson;
	TrackLog *deserialized;
}
@end

#define DATE_LONG 1411065116782
#define DATE_ISO @"2014-09-18T11:31:56.782-07:00"
#define DATE_ZULU @"2014-09-18T11:31:56.782Z"
#define TEST_KEY @"date"

@implementation TrackLogTest

- (void)setUp
{
	[super setUp];
	NSString *pathToResource = [[NSBundle bundleForClass:self.class] pathForResource:@"track_log" ofType:@"json"];
	NSError *error = nil;
	sampleJson = [NSString stringWithContentsOfFile:pathToResource encoding:NSUTF8StringEncoding error:&error];
	if(error) {
		XCTFail(@"Failed to load file: contests.json: %@", error.localizedDescription);
	}
	NSDictionary *dict = [Serializer fromJsonString:sampleJson];
	deserialized = [TrackLog fromDictionary:dict];
	XCTAssertNotNil(deserialized, @"The TrackLog failed to deserialize properly");
}

- (void)tearDown
{
    // Put teardown code here; it will be run once, after the last test case.
    [super tearDown];
}

-(void)testTime {
	XCTAssertEqualWithAccuracy(1.419974312334718E12, deserialized.time, 0.01, @"Failed to properly deserialize the time");
}

-(void)testClass {
	XCTAssertEqualObjects(@"", deserialized.class, @"Failed to properly deserialize the class");
}

-(void)testMethod {
	XCTAssertEqualObjects(@"", deserialized.method, @"Failed to properly deserialize the method");
}

-(void)testLine {
	XCTAssertEqual((NSInteger)1234, deserialized.line, @"Failed to properly deserialize the line");
}

-(void)testLevel {
	XCTAssertEqualObjects(@"DEBUG", deserialized.level, @"Failed to properly deserialize the level");
}

-(void)testTheDescription {
	XCTAssertEqualObjects(@"something happened", deserialized.theDescription, @"Failed to properly deserialize the theDescription");
}

@end
