//
//  TrackKeyPointsTest.m
//
//  Generated by JSON Model Generator v0.0.2 on Tue Jan 13 16:44:19 MST 2015.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <XCTest/XCTest.h>
#import "TrackKeyPoints.h"
#import "Serializer.h"

@interface TrackKeyPointsTest : XCTestCase{
	NSString *sampleJson;
	TrackKeyPoints *deserialized;
}
@end

#define DATE_LONG 1411065116782
#define DATE_ISO @"2014-09-18T11:31:56.782-07:00"
#define DATE_ZULU @"2014-09-18T11:31:56.782Z"
#define TEST_KEY @"date"

@implementation TrackKeyPointsTest

- (void)setUp
{
	[super setUp];
	NSString *pathToResource = [[NSBundle bundleForClass:self.class] pathForResource:@"track_key_points" ofType:@"json"];
	NSError *error = nil;
	sampleJson = [NSString stringWithContentsOfFile:pathToResource encoding:NSUTF8StringEncoding error:&error];
	if(error) {
		XCTFail(@"Failed to load file: contests.json: %@", error.localizedDescription);
	}
	NSDictionary *dict = [Serializer fromJsonString:sampleJson];
	deserialized = [TrackKeyPoints fromDictionary:dict];
	XCTAssertNotNil(deserialized, @"The TrackKeyPoints failed to deserialize properly");
}

- (void)tearDown
{
    // Put teardown code here; it will be run once, after the last test case.
    [super tearDown];
}

-(void)testDir {
	XCTAssertEqual((NSInteger)0, deserialized.dir, @"Failed to properly deserialize the dir");
}

-(void)testDist {
	XCTAssertEqualWithAccuracy(1603.783661514272, deserialized.dist, 0.01, @"Failed to properly deserialize the dist");
}

-(void)testDuration {
	XCTAssertEqualWithAccuracy(772.1015610694885, deserialized.duration, 0.01, @"Failed to properly deserialize the duration");
}

-(void)testIdxEnd {
	XCTAssertEqual((NSInteger)116, deserialized.idxEnd, @"Failed to properly deserialize the idxEnd");
}

-(void)testIdxStart {
	XCTAssertEqual((NSInteger)0, deserialized.idxStart, @"Failed to properly deserialize the idxStart");
}

-(void)testMaxElev {
	XCTAssertEqualWithAccuracy(3243.417810440063, deserialized.maxElev, 0.01, @"Failed to properly deserialize the maxElev");
}

-(void)testMaxSpeed {
	XCTAssertEqualWithAccuracy(5.884496612592504, deserialized.maxSpeed, 0.01, @"Failed to properly deserialize the maxSpeed");
}

-(void)testMinElev {
	XCTAssertEqualWithAccuracy(2767.097253799438, deserialized.minElev, 0.01, @"Failed to properly deserialize the minElev");
}

-(void)testVDelta {
	XCTAssertEqualWithAccuracy(472.719482421875, deserialized.vDelta, 0.01, @"Failed to properly deserialize the vDelta");
}

-(void)testTheDescription {
	XCTAssertEqualObjects(@"blah", deserialized.theDescription, @"Failed to properly deserialize the theDescription");
}

-(void)testType {
	XCTAssertEqualObjects(@"system", deserialized.type, @"Failed to properly deserialize the type");
}

@end
