//
//  TrackKeyPointsTest.m
//
//  Generated by JSON Model Generator v0.0.2 on Sun Dec 28 07:17:18 MST 2014.
//    https://github.com/intere/generator-json-models
//
//    The generator tool is licensed under the LGPL: http://www.gnu.org/licenses/lgpl-3.0.html#content
//
//

#import <XCTest/XCTest.h>
#import "TrackKeyPoints.h"
#import "Serializer.h"

@interface TrackKeyPointsTest : XCTestCase{
	NSString *sampleJson;
	TrackKeyPoints *deserialized;
}
@end

#define DATE_LONG 1411065116782
#define DATE_ISO @"2014-09-18T11:31:56.782-07:00"
#define DATE_ZULU @"2014-09-18T11:31:56.782Z"
#define TEST_KEY @"date"

@implementation TrackKeyPointsTest

- (void)setUp
{
	[super setUp];
	NSString *pathToResource = [[NSBundle bundleForClass:self.class] pathForResource:@"track_key_points" ofType:@"json"];
	NSError *error = nil;
	sampleJson = [NSString stringWithContentsOfFile:pathToResource encoding:NSUTF8StringEncoding error:&error];
	if(error) {
		XCTFail(@"Failed to load file: contests.json: %@", error.localizedDescription);
	}
	NSDictionary *dict = [Serializer fromJsonString:sampleJson];
	deserialized = [TrackKeyPoints fromDictionary:dict];
	XCTAssertNotNil(deserialized, @"The TrackKeyPoints failed to deserialize properly");
}

- (void)tearDown
{
    // Put teardown code here; it will be run once, after the last test case.
    [super tearDown];
}

-(void)testDir {
	XCTAssertEqual((NSInteger)0, deserialized.dir, @"Failed to properly deserialize the dir");
}

-(void)testDist {
	XCTAssertEqualWithAccuracy(1492.232601042096, deserialized.dist, 0.01, @"Failed to properly deserialize the dist");
}

-(void)testDuration {
	XCTAssertEqualWithAccuracy(475.0239629745483, deserialized.duration, 0.01, @"Failed to properly deserialize the duration");
}

-(void)testIdxEnd {
	XCTAssertEqual((NSInteger)121, deserialized.idxEnd, @"Failed to properly deserialize the idxEnd");
}

-(void)testIdxStart {
	XCTAssertEqual((NSInteger)0, deserialized.idxStart, @"Failed to properly deserialize the idxStart");
}

-(void)testMaxElev {
	XCTAssertEqualWithAccuracy(3260.909265518188, deserialized.maxElev, 0.01, @"Failed to properly deserialize the maxElev");
}

-(void)testMaxSpeed {
	XCTAssertEqualWithAccuracy(4.044931513403013, deserialized.maxSpeed, 0.01, @"Failed to properly deserialize the maxSpeed");
}

-(void)testMinElev {
	XCTAssertEqualWithAccuracy(2788.198328018188, deserialized.minElev, 0.01, @"Failed to properly deserialize the minElev");
}

-(void)testVDelta {
	XCTAssertEqualWithAccuracy(471.81884765625, deserialized.vDelta, 0.01, @"Failed to properly deserialize the vDelta");
}

@end
